server:
  error:
    include-stacktrace: never

# expose actuator for SBA
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  zipkin:
    baseUrl:  ${ZIPKIN_URL:http://localhost:9411}
  jmx:
    enabled: false

eureka:
  instance:
    # to allow SBA access this service
    metadata-map:
      user.name: "actuator"
      user.password: "{cipher}a4b40ea05df6dd7eb0d2d0504958585359f410d49441742accded740a20096e7"

---

spring:
  profiles: dev
  sleuth.sampler.probability: 1.0

server:
  error:
    include-stacktrace: always
