server.port: ${GAME_SERVICE_PORT:40002}

spring:
  profiles:
    include: microservice
  data:
    mongodb:
      host: ${MONGO_HOST:localhost} # for dev
      database: ${MONGO_DATABASE:tictactoe}

eureka:
  instance:
    # to allow SBA access this service
    metadata-map:
      user.name: "actuator"
      user.password: "{cipher}8f67106e070e0f99bc30f70e738a707e2d3c9f7855c1ecf26ec8932ce3fa4dbb"
