server.port: ${GAME_SERVICE_PORT:40002}

spring:
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl:  ${ZIPKIN_URL:http://mydomain:9411}
  data:
    mongodb:
      username: ${MONGO_INITDB_ROOT_USERNAME:tictactoe}
      password: "{cipher}879be42b83745787563d46c454edc5496925c6162c3b792a135601c30eb74d9a" # 123
      host: ${MONGODB_HOST:localhost} # for dev
      database: ${MONGO_INITDB_DATABASE:tictactoe}

eureka:
  instance:
    # to allow SBA access this service
    metadata-map:
      user.name: "actuator"
      user.password: "{cipher}8f67106e070e0f99bc30f70e738a707e2d3c9f7855c1ecf26ec8932ce3fa4dbb" # actuator

# expose actuator for SBA
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tictactoecorp: DEBUG