server.port: ${PORT:40001}

spring:
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl:  http://mydomain:9411
  data:
    mongodb:
      username: "tictactoe"
      password: "{cipher}879be42b83745787563d46c454edc5496925c6162c3b792a135601c30eb74d9a" # 123
      host: "localhost"
      port: 27017
      database: "tictactoe"


#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tictactoecorp: DEBUG