server.port: ${USER_SERVICE_PORT:40001}

spring:
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl:  ${ZIPKIN_URL:http://mydomain:9411}
  data:
    mongodb:
      host: ${MONGO_HOST:localhost} # for dev
      database: ${MONGO_DATABASE:tictactoe}
