server.port: ${PORT:40001}

spring:
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl:  http://mydomain:9411
  data:
    mongodb:
      username: "tictactoe"
      password: "{cipher}879be42b83745787563d46c454edc5496925c6162c3b792a135601c30eb74d9a" # 123
      host: "localhost"
      port: 27017
      database: "tictactoe"
#  security:
#    user:
#      name: "user"
#      password: "{cipher}aac109803d87ddf8b7ff7e589569d1dcf16bf12abb3be400269399baebc3854e" # password
#
#eureka:
#  instance:
#    metadata-map:
#      user.name: ${spring.security.user.name}
#      user.password: ${spring.security.user.password}
#
#management:
#  endpoints:
#    web.exposure.include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tictactoecorp: DEBUG