server.port: ${PORT:40010}

spring:
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl:  http://mydomain:9411

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tictactoecorp: DEBUG