server.port: ${PORT:40010}

spring:
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl:  http://mydomain:9411

eureka:
  instance:
    preferIpAddress: true
    metadata-map:
      user.name: ${ACTUATOR_USERNAME:actuator}
      user.password: ${ACTUATOR_PASSWORD:actuator}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#Setting logging levels
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.tictactoecorp: DEBUG