server.port: ${PORT:40010}

spring:
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl:  ${ZIPKIN_URL:http://mydomain:9411}

eureka:
  instance:
    metadata-map:
      user.name: ${ACTUATOR_USERNAME:actuator}
      user.password: "{cipher}8f67106e070e0f99bc30f70e738a707e2d3c9f7855c1ecf26ec8932ce3fa4dbb"

# expose actuator for SBA
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#Setting logging levels
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.tictactoecorp: DEBUG